/*
 * Customer Management Service
 * A service for placing orders and transactions
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hariprasath.narayanasamy@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CustomerManagementService);
  }
}(this, function(expect, CustomerManagementService) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('OrderInfo', function() {
      beforeEach(function() {
        instance = new CustomerManagementService.OrderInfo();
      });

      it('should create an instance of OrderInfo', function() {
        // TODO: update the code to test OrderInfo
        expect(instance).to.be.a(CustomerManagementService.OrderInfo);
      });

      it('should have the property modelId (base name: "model_id")', function() {
        // TODO: update the code to test the property modelId
        expect(instance).to.have.property('modelId');
        // expect(instance.modelId).to.be(expectedValueLiteral);
      });

      it('should have the property userId (base name: "user_id")', function() {
        // TODO: update the code to test the property userId
        expect(instance).to.have.property('userId');
        // expect(instance.userId).to.be(expectedValueLiteral);
      });

      it('should have the property transactionId (base name: "transaction_id")', function() {
        // TODO: update the code to test the property transactionId
        expect(instance).to.have.property('transactionId');
        // expect(instance.transactionId).to.be(expectedValueLiteral);
      });

      it('should have the property offerId (base name: "offer_id")', function() {
        // TODO: update the code to test the property offerId
        expect(instance).to.have.property('offerId');
        // expect(instance.offerId).to.be(expectedValueLiteral);
      });

      it('should have the property colour (base name: "colour")', function() {
        // TODO: update the code to test the property colour
        expect(instance).to.have.property('colour');
        // expect(instance.colour).to.be(expectedValueLiteral);
      });

    });
  });

}));
