/*
 * Customer Management Service
 * A service for placing orders and transactions
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hariprasath.narayanasamy@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CustomerManagementService);
  }
}(this, function(expect, CustomerManagementService) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('TransactionDetails', function() {
      beforeEach(function() {
        instance = new CustomerManagementService.TransactionDetails();
      });

      it('should create an instance of TransactionDetails', function() {
        // TODO: update the code to test TransactionDetails
        expect(instance).to.be.a(CustomerManagementService.TransactionDetails);
      });

      it('should have the property transactionId (base name: "transaction_id")', function() {
        // TODO: update the code to test the property transactionId
        expect(instance).to.have.property('transactionId');
        // expect(instance.transactionId).to.be(expectedValueLiteral);
      });

    });
  });

}));
