/*
 * Customer Management Service
 * A service for placing orders and transactions
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hariprasath.narayanasamy@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The OrderInfo model module.
 * @module model/OrderInfo
 * @version 1.0.0
 */
export class OrderInfo {
  /**
   * Constructs a new <code>OrderInfo</code>.
   * @alias module:model/OrderInfo
   * @class
   * @param modelId {String} model id
   * @param userId {String} User who booked the vehicle
   * @param transactionId {String} 
   * @param offerId {String} 
   * @param colour {module:model/OrderInfo.ColourEnum} 
   */
  constructor(modelId, userId, transactionId, offerId, colour) {
    this.modelId = modelId;
    this.userId = userId;
    this.transactionId = transactionId;
    this.offerId = offerId;
    this.colour = colour;
  }

  /**
   * Constructs a <code>OrderInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrderInfo} obj Optional instance to populate.
   * @return {module:model/OrderInfo} The populated <code>OrderInfo</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OrderInfo();
      if (data.hasOwnProperty('model_id'))
        obj.modelId = ApiClient.convertToType(data['model_id'], 'String');
      if (data.hasOwnProperty('user_id'))
        obj.userId = ApiClient.convertToType(data['user_id'], 'String');
      if (data.hasOwnProperty('transaction_id'))
        obj.transactionId = ApiClient.convertToType(data['transaction_id'], 'String');
      if (data.hasOwnProperty('offer_id'))
        obj.offerId = ApiClient.convertToType(data['offer_id'], 'String');
      if (data.hasOwnProperty('colour'))
        obj.colour = ApiClient.convertToType(data['colour'], 'String');
    }
    return obj;
  }
}

/**
 * model id
 * @member {String} modelId
 */
OrderInfo.prototype.modelId = undefined;

/**
 * User who booked the vehicle
 * @member {String} userId
 */
OrderInfo.prototype.userId = undefined;

/**
 * @member {String} transactionId
 */
OrderInfo.prototype.transactionId = undefined;

/**
 * @member {String} offerId
 */
OrderInfo.prototype.offerId = undefined;

/**
 * Allowed values for the <code>colour</code> property.
 * @enum {String}
 * @readonly
 */
OrderInfo.ColourEnum = {
  /**
   * value: "Radiant Red"
   * @const
   */
  radiantRed: "Radiant Red",

  /**
   * value: "Pearl White"
   * @const
   */
  pearlWhite: "Pearl White",

  /**
   * value: "Mat black"
   * @const
   */
  matBlack: "Mat black",

  /**
   * value: "Brilliant Blue"
   * @const
   */
  brilliantBlue: "Brilliant Blue",

  /**
   * value: "Cosmic Cyan"
   * @const
   */
  cosmicCyan: "Cosmic Cyan"
};
/**
 * @member {module:model/OrderInfo.ColourEnum} colour
 */
OrderInfo.prototype.colour = undefined;

