/*
 * Customer Management Service
 * A service for placing orders and transactions
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hariprasath.narayanasamy@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The OrderDetails model module.
 * @module model/OrderDetails
 * @version 1.0.0
 */
export class OrderDetails {
  /**
   * Constructs a new <code>OrderDetails</code>.
   * @alias module:model/OrderDetails
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>OrderDetails</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OrderDetails} obj Optional instance to populate.
   * @return {module:model/OrderDetails} The populated <code>OrderDetails</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OrderDetails();
    }
    return obj;
  }
}
