/*
 * Customer Management Service
 * A service for placing orders and transactions
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hariprasath.narayanasamy@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The TransactionInfo model module.
 * @module model/TransactionInfo
 * @version 1.0.0
 */
export class TransactionInfo {
  /**
   * Constructs a new <code>TransactionInfo</code>.
   * @alias module:model/TransactionInfo
   * @class
   * @param modelId {String} 
   * @param userId {String} 
   * @param transactionAmount {Number} 
   */
  constructor(modelId, userId, transactionAmount) {
    this.modelId = modelId;
    this.userId = userId;
    this.transactionAmount = transactionAmount;
  }

  /**
   * Constructs a <code>TransactionInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TransactionInfo} obj Optional instance to populate.
   * @return {module:model/TransactionInfo} The populated <code>TransactionInfo</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TransactionInfo();
      if (data.hasOwnProperty('model_id'))
        obj.modelId = ApiClient.convertToType(data['model_id'], 'String');
      if (data.hasOwnProperty('user_id'))
        obj.userId = ApiClient.convertToType(data['user_id'], 'String');
      if (data.hasOwnProperty('transaction_amount'))
        obj.transactionAmount = ApiClient.convertToType(data['transaction_amount'], 'Number');
      if (data.hasOwnProperty('date'))
        obj._date = ApiClient.convertToType(data['date'], 'String');
      if (data.hasOwnProperty('timing'))
        obj.timing = ApiClient.convertToType(data['timing'], 'Number');
      if (data.hasOwnProperty('account_from'))
        obj.accountFrom = ApiClient.convertToType(data['account_from'], 'String');
      if (data.hasOwnProperty('account_to'))
        obj.accountTo = ApiClient.convertToType(data['account_to'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} modelId
 */
TransactionInfo.prototype.modelId = undefined;

/**
 * @member {String} userId
 */
TransactionInfo.prototype.userId = undefined;

/**
 * @member {Number} transactionAmount
 */
TransactionInfo.prototype.transactionAmount = undefined;

/**
 * @member {String} _date
 */
TransactionInfo.prototype._date = undefined;

/**
 * @member {Number} timing
 */
TransactionInfo.prototype.timing = undefined;

/**
 * @member {String} accountFrom
 */
TransactionInfo.prototype.accountFrom = undefined;

/**
 * @member {String} accountTo
 */
TransactionInfo.prototype.accountTo = undefined;

