/*
 * Customer Management Service
 * A service for placing orders and transactions
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hariprasath.narayanasamy@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {TransactionInfo} from './TransactionInfo';

/**
 * The TransactionDetails model module.
 * @module model/TransactionDetails
 * @version 1.0.0
 */
export class TransactionDetails extends TransactionInfo {
  /**
   * Constructs a new <code>TransactionDetails</code>.
   * @alias module:model/TransactionDetails
   * @class
   * @extends module:model/TransactionInfo
   * @param modelId {} 
   * @param userId {} 
   * @param transactionAmount {} 
   */
  constructor(modelId, userId, transactionAmount) {
    super(modelId, userId, transactionAmount);
  }

  /**
   * Constructs a <code>TransactionDetails</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TransactionDetails} obj Optional instance to populate.
   * @return {module:model/TransactionDetails} The populated <code>TransactionDetails</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TransactionDetails();
      TransactionInfo.constructFromObject(data, obj);
      if (data.hasOwnProperty('transaction_id'))
        obj.transactionId = ApiClient.convertToType(data['transaction_id'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} transactionId
 */
TransactionDetails.prototype.transactionId = undefined;

