/*
 * Customer Management Service
 * A service for placing orders and transactions
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hariprasath.narayanasamy@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CustomerManagementService);
  }
}(this, function(expect, CustomerManagementService) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CustomerManagementService.OrdersApi();
  });

  describe('(package)', function() {
    describe('OrdersApi', function() {
      describe('bookingCar', function() {
        it('should call bookingCar successfully', function(done) {
          // TODO: uncomment, update parameter values for bookingCar call and complete the assertions
          /*
          var opts = {};

          instance.bookingCar(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(CustomerManagementService.Model201OrderCreatedResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteOrder', function() {
        it('should call deleteOrder successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteOrder call and complete the assertions
          /*

          instance.deleteOrder(orderId, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(CustomerManagementService.Model200OrderDeletedResponse);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('ordersGet', function() {
        it('should call ordersGet successfully', function(done) {
          // TODO: uncomment ordersGet call and complete the assertions
          /*

          instance.ordersGet(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(CustomerManagementService.OrderDetails);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
